"""empty message

Revision ID: 01c8ed6c7476
Revises: a9e33483619c
Create Date: 2020-04-07 03:24:54.221358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c8ed6c7476'
down_revision = 'a9e33483619c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('routes_endPos_fkey', 'routes', type_='foreignkey')
    op.drop_constraint('routes_startPos_fkey', 'routes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('routes_startPos_fkey', 'routes', 'points', ['startPos'], ['id'])
    op.create_foreign_key('routes_endPos_fkey', 'routes', 'points', ['endPos'], ['id'])
    # ### end Alembic commands ###
