"""empty message

Revision ID: 32f56bacbdb2
Revises: 30b6137fa284
Create Date: 2020-04-07 03:35:57.736631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f56bacbdb2'
down_revision = '30b6137fa284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('endPos_id', sa.Integer(), nullable=False))
    op.add_column('routes', sa.Column('startPos_id', sa.Integer(), nullable=False))
    op.drop_constraint('routes_endPos_fkey', 'routes', type_='foreignkey')
    op.drop_constraint('routes_startPos_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'points', ['endPos_id'], ['id'])
    op.create_foreign_key(None, 'routes', 'points', ['startPos_id'], ['id'])
    op.drop_column('routes', 'startPos')
    op.drop_column('routes', 'endPos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('endPos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('startPos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_startPos_fkey', 'routes', 'points', ['startPos'], ['id'])
    op.create_foreign_key('routes_endPos_fkey', 'routes', 'points', ['endPos'], ['id'])
    op.drop_column('routes', 'startPos_id')
    op.drop_column('routes', 'endPos_id')
    # ### end Alembic commands ###
