"""empty message

Revision ID: 49d2635f19b9
Revises: ccb3c8363275
Create Date: 2020-03-23 16:32:36.597108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d2635f19b9'
down_revision = 'ccb3c8363275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'purpose',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'purpose',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
