"""empty message

Revision ID: ccb3c8363275
Revises: 33c0dc5a36e0
Create Date: 2020-03-23 15:06:23.579660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb3c8363275'
down_revision = '33c0dc5a36e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'routes', 'users', ['user_id'], ['id'])
    op.alter_column('routes', 'purpose', existing_type=sa.Boolean(), type_=sa.String(255))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.alter_column('routes', 'purpose', existing_type=sa.String(255), type_=sa.Boolean())
    # ### end Alembic commands ###
